### ISSUE TITLE
Migrate public facing documents to accessible format

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/gin#15]
```[tasklist]
### Tasks
- [ ] https://github.com/geobtaa/gin/issues/3
- [ ] https://github.com/geobtaa/gin/issues/16
- [ ] https://github.com/geobtaa/gin/issues/17
- [ ] https://github.com/geobtaa/gin/issues/5
- [ ] https://github.com/geobtaa/gin/issues/32
- [ ] https://github.com/geobtaa/gin/issues/31
```

**Comment by karenmajewicz** [comment]
New site is live with all content migrated: https://gin.btaa.org
