### ISSUE TITLE
Migrate tutorials to markdown/github pages

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/gin#16]
```[tasklist]
### Tasks
- [ ] https://github.com/geobtaa/tutorials/issues/1
- [ ] https://github.com/geobtaa/tutorials/issues/2
- [ ] https://github.com/geobtaa/tutorials/issues/3
- [ ] https://github.com/geobtaa/tutorials/issues/4
- [ ] https://github.com/geobtaa/tutorials/issues/5
- [ ] https://github.com/geobtaa/tutorials/issues/6
- [ ] https://github.com/geobtaa/tutorials/issues/7
- [ ] https://github.com/geobtaa/tutorials/issues/8
- [ ] https://github.com/geobtaa/tutorials/issues/9
- [ ] https://github.com/geobtaa/tutorials/issues/10
- [ ] https://github.com/geobtaa/tutorials/issues/11
```

**Comment by karenmajewicz** [comment]
https://geobtaa.github.io/gin/tutorials/
